PELICULAS/PELICULAS/urls.py
from django.urls import path
from django.contrib import admin
from moduloPeliculas import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PeliculaListView, name='pelicula-list'),  
    path('agregarpelicula/', views.agregar_pelicula, name='agregarpelicula'),
    path('<int:id>/', views.pelicula_detail, name='pelicula-detail'),
    path('editar/<int:id>/', views.editar_pelicula, name='editar-pelicula'),
    path('eliminar/<int:id>/', views.eliminar_pelicula, name='eliminar-pelicula'),
    path('gestionpeliculas/', views.PeliculaListCrud, name='gestion_peliculas'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PELICULAS/moduloPeliculas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Pelicula(models.Model):
    SUCURSAL_CHOICES = [
        ('PlazaOeste', 'Plaza Oeste'),
        ('MallAraucoMaipu', 'Mall Arauco Maipu'),
        ('CinepolisMaipu', 'Cinepolis Maipu'),
        ('PlazaOeste', 'Plaza Oeste'),
        ('PlazaVespucio', 'Plaza Vespucio'),
    ]

    GENERO_CHOICES = [
        ('Accion', 'Accion'),
        ('Comedia', 'Comedia'),
        ('Drama', 'Drama'),
        ('Suspenso', 'Suspenso'),
        ('Crimen', 'Crimen'),
        ('Romance', 'Romance'),
        ('Terror', 'Terror'),
        ('Musical', 'Musical'),
    ]

    CLASIFICACION_CHOICES = [
        ('TE', 'TE'),
        ('TE+7', 'TE+7'),
        ('+14', '+14'),
        ('+18', '+18'),
    ]

    sucursal = models.CharField(max_length=100, choices=SUCURSAL_CHOICES)  # Asegúrate de que el campo esté correctamente definido
    nombre = models.CharField(max_length=50, help_text='Nombre de la pelicula')
    genero = models.CharField(max_length=20, choices=GENERO_CHOICES, help_text='Genero de la pelicula', blank=False)
    clasificacion = models.CharField(max_length=8, choices=CLASIFICACION_CHOICES, help_text='Clasificacion de la pelicula', blank=False)
    duracion = models.PositiveIntegerField(help_text='Tiempo de duración en minutos')
    resena = models.TextField(blank=True, help_text='Breve reseña de la pelicula')
    sala = models.IntegerField(validators=[MinValueValidator(1, message="El número de sala debe ser mayor o igual a 1."), 
                                           MaxValueValidator(15, message="El número de sala debe ser menor o igual a 15.")], help_text='Sala en la que se exhibe')
    fecha_exhibicion = models.DateField(help_text='Fecha de exhibición', blank=False)
    hora_exhibicion = models.TimeField(help_text='Hora de exhibición', blank=False)
    valor_ticket = models.PositiveIntegerField(help_text='Valor del ticket')
    imagen = models.ImageField(upload_to='peliculas/')

    def __str__(self):
        return self.nombre

PELICULAS/moduloPeliculas/forms.py
from django import forms
from .models import Pelicula
from datetime import date

class PeliculaForm(forms.ModelForm):
    class Meta:
        model = Pelicula
        fields = ['sucursal', 'nombre', 'genero', 'clasificacion', 'duracion', 
                  'resena', 'sala', 'fecha_exhibicion', 'hora_exhibicion', 'valor_ticket', 'imagen']
        widgets = {
            'sucursal': forms.Select(attrs={'class':'form-control'}),
            'nombre': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nombre de la pelicula'}),
            'genero': forms.Select(attrs={'class':'form-control'}),
            'clasificacion': forms.Select(attrs={'class':'form-control'}),
            'duracion': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Tiempo de duración en minutos'}),
            'resena': forms.Textarea(attrs={'class':'form-control', 'rows' : 3, 'placeholder':'Breve reseña del contenido de la pelicula'}),
            'sala': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Sala en la que se exhibe'}),
            'fecha_exhibicion': forms.DateInput(attrs={'type':'date','class':'form-control'}),
            'hora_exhibicion': forms.TimeInput(attrs={'type':'time','class':'form-control'}),
            'valor_ticket': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Valor del ticket'}),
            'imagen': forms.ClearableFileInput(attrs={'accept':'image/*', 'directory': 'peliculas'}),
        }

    def clean_salas(self):
        sala = self.cleaned_data['sala']
        if sala < 1 or sala > 15:
            raise forms.ValidationError("El número de sala debe estar entre 1 y 15")
        return sala
    
    def clean_fecha_exhibicion(self):
        fecha_exhibicion = self.cleaned_data['fecha_exhibicion']
        if fecha_exhibicion <= date.today():
            raise forms.ValidationError("La fecha de exhibición debe ser posterior a la fecha actual")
        return fecha_exhibicion

PELICULAS/moduloPeliculas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Pelicula
from .forms import PeliculaForm
from django.contrib import messages

# Create your views here.

def PeliculaListView(request):
    peliculas = Pelicula.objects.all()
    peliculas = peliculas.order_by('nombre')
    peliculas = {"peliculas":peliculas}
    return render(request, "peliculas_list.html", peliculas)

def PeliculaListCrud(request):
    peliculas = Pelicula.objects.all()
    peliculas = peliculas.order_by('nombre')
    peliculas = {"peliculas":peliculas}
    return render(request, "peliculas_crud.html", peliculas)

def pelicula_detail(request, id):
    pelicula = get_object_or_404(Pelicula, id=id)
    return render(request, 'pelicula_details.html', {'pelicula': pelicula}) 

def agregar_pelicula(request):
    if request.method == 'POST':
        form = PeliculaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            #redirige a la vista lista_articulos
            return PeliculaListView(request)
    else:
        form = PeliculaForm()
    return render(request, 'pelicula_form.html', {'form': form})

def eliminar_pelicula(request, id):
    pelicula = Pelicula.objects.get(id=id)
    pelicula.delete()
    # Agrega un mensaje de confirmación
    messages.success(request, f'Se haeliminado a {pelicula.nombre}')
    return redirect('pelicula-list')

def editar_pelicula(request, id):
    pelicula = get_object_or_404(Pelicula, id=id)
    if request.method == 'POST':
        form = PeliculaForm(request.POST, request.FILES, instance=pelicula)
        if form.is_valid():
            form.save()
            print('Formulario válido. Película guardada.')
            return redirect('pelicula-list') 
        else:
            print('Formulario no inválido. Errores:', form.errors)
    else:
        form = PeliculaForm(instance=pelicula)
    return render(request, 'pelicula_form.html', {'form': form})

PELICULAS/moduloPeliculas/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <style>
        body{
            background-color: #161435;
        }
        header{
            background-color: #343a40;
            color: white;
            padding: 20px;
        }
        footer{
            background-color: #343a40;
            color: white;
            padding: 10px;
            text-align: center;
        }

        .card {
            margin: 10px;
            opacity: 0.9;
        }

        .card-img-top {
            height: 300px;
            object-fit: cover;
            padding: 1px;
        }

    </style>
    <title>{% block title %}Django Peliculas{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pelicula-list' %}">Peliculas Django</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pelicula-list' %}">Catálogo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'agregarpelicula' %}">Nueva Película</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gestion_peliculas' %}">Gestión de Películas</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main>
            {% block content %} {% endblock %}
        </main>
    </div>
    <!-- Agrego los scripts de Bootstrap y jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

PELICULAS/moduloPeliculas/templates/pelicula_details.html
<!-- templates/pelicula_detail.html -->
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="mb-4" style="color: white;">Detalle de Película: {{ pelicula.nombre }}</h2>
    <div class="card" style="width: 600px;">
        <div class="card-body">
            {% if pelicula.imagen %}
                <img src="{{ pelicula.imagen.url }}" alt="{{ pelicula.nombre }}" class="img-fluid mb-4" style="width: 300px;">
            {% else %}
                <p class="mb-4">No hay imagen disponible.</p>
            {% endif %}
            <p class="card-text"><strong>Sucursal:</strong> {{ pelicula.sucursal }}</p>
            <p class="card-text"><strong>Género:</strong> {{ pelicula.get_genero_display }}</p>
            <p class="card-text"><strong>Clasificación:</strong> {{ pelicula.get_clasificacion_display }}</p>
            <p class="card-text"><strong>Duración:</strong> {{ pelicula.duracion }} minutos</p>
            <p class="card-text"><strong>Reseña:</strong> {{ pelicula.resena }}</p>
            <p class="card-text"><strong>Sala:</strong> {{ pelicula.sala }}</p>
            <p class="card-text"><strong>Fecha de Exhibición:</strong> {{ pelicula.fecha_exhibicion }}</p>           
            <p class="card-text"><strong>Hora de Exhibición:</strong> {{ pelicula.hora_exhibicion }}</p>
            <p class="card-text"><strong>Valor del Ticket:</strong> {{ pelicula.valor_ticket }}</p>
        </div>
    </div>
    <div class="container mt-5">
        <a href="{% url 'editar-pelicula' id=pelicula.id %}" class="btn btn-warning">Editar</a>
        <a href="{% url 'eliminar-pelicula' id=pelicula.id %}" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar a {{ pelicula.nombre }}?')">Eliminar</a>
        <a href="{% url 'pelicula-list' %}" class="btn btn-primary">Volver al Listado de Películas</a>
    </div>
</div>
{% endblock %}

PELICULAS/moduloPeliculas/templates/pelicula_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5" style="background-color: rgb(21, 53, 157); border-radius: 5px;">
        <h2 class="mb-4 text-white">{% if form.instance.id %}Editar{% else %}Crear{% endif %} Película</h2>
        <form method="post" enctype="multipart/form-data" class="my-form">
            {% csrf_token %}
            <div class="mb-3">
                <label for="{{ form.sucursal.id_for_label }}" class="form-label text-white">Sucursal de la cadena:</label>
                {{ form.sucursal }}
            </div>
            <div class="mb-3">
                <label for="{{ form.nombre.id_for_label }}" class="form-label text-white">Nombre de la película:</label>
                {{ form.nombre }}
            </div>
            <div class="mb-3">
                <label for="{{ form.genero.id_for_label }}" class="form-label text-white">Género:</label>
                {{ form.genero }}
            </div>
            <div class="mb-3">
                <label for="{{ form.clasificacion.id_for_label }}" class="form-label text-white">Clasificación:</label>
                {{ form.clasificacion }}
            </div>
            <div class="mb-3">
                <label for="{{ form.duracion.id_for_label }}" class="form-label text-white">Duración (minutos):</label>
                {{ form.duracion }}
            </div>
            <div class="mb-3">
                <label for="{{ form.resena.id_for_label }}" class="form-label text-white">Reseña:</label>
                {{ form.resena }}
            </div>
            <div class="mb-3">
                <label for="{{ form.sala.id_for_label }}" class="form-label text-white">Sala en la que se exhibe:</label>
                {{ form.sala }}
                {% for error in form.sala.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="mb-3">
                <label for="{{ form.fecha_exhibicion.id_for_label }}" class="form-label text-white">Fecha de la exhibición:</label>
                {{ form.fecha_exhibicion }}
            </div>
            <div class="mb-3">
                <label for="{{ form.hora_exhibicion.id_for_label }}" class="form-label text-white">Hora de la exhibición:</label>
                {{ form.hora_exhibicion }}
            </div>
            <div class="mb-3">
                <label for="{{ form.valor_ticket.id_for_label }}" class="form-label text-white">Valor del ticket:</label>
                {{ form.valor_ticket }}
            </div>
            <div class="mb-3">
                <label for="{{ form.imagen.id_for_label }}" class="form-label text-white">Imagen de la película:</label>
                {{ form.imagen }}
            </div>
            <button type="submit" class="btn btn-primary">Guardar cambios</button>
            <br>
            <a href="{% url 'pelicula-list' %}" class="btn btn-secondary mt-3">Volver al Listado de Películas</a>
            <br>
            <br>
            {% if form.errors %}
            <div class="alert alert-danger mt-3" role="alert">
                <strong class="text-white">Por favor, corrija los siguientes errores en el formulario:</strong>
                <ul class="text-white">
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <li>{{ field|title }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </form>
    </div>
    <br><br>
{% endblock %}

PELICULAS/moduloPeliculas/templates/peliculas_crud.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <h2 style="color: white;">Gestión Películas</h2>
</div>
<div class="table-responsive" style="background-color: white;">
    <table class="table table-bordered table-striped text-center">
        <thead class="thead-dark">
            <tr>
                <th>Afiche</th>
                <th>Nombre</th>
                <th>Género</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for pelicula in peliculas %}
                <tr>
                    <td class="align-middle">
                        {% if pelicula.imagen %}
                            <img src="{{ pelicula.imagen.url }}" alt="{{ pelicula.nombre }}" style="max-width: 180px; max-height: 230px;">
                        {% else %}
                            <img src="{% static 'images/not-found.jpg' %}" alt="">
                        {% endif %}
                    </td>
                    <td class="align-middle">{{ pelicula.nombre }}</td>
                    <td class="align-middle">{{ pelicula.genero }}</td>
                    <td class="align-middle">
                        <a href="{% url 'editar-pelicula' id=pelicula.id %}" class="btn btn-warning btn-sm"><i class="fas fa-pencil-alt"></i></a>
                        <a href="{% url 'eliminar-pelicula' id=pelicula.id %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas eliminar a {{ pelicula.nombre }}?')"><i class="fas fa-times"></i></a>
                        <a href="{% url 'pelicula-detail' id=pelicula.id %}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

PELICULAS/moduloPeliculas/templates/peliculas_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    /* En tu archivo styles.css */
    .card {
        height: 550px;
        width: 300px;
        transition: transform 0.3s ease; /* Agregamos una transición a la propiedad transform */
    }
    .card:hover {
        transform: scale(1.05); /* Escalamos el card al hacer hover */
    }
    .card img {
        max-height: 100%;
    }
    .card-body {
        text-align: center;
    }
    .card-body h5 {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
    .card-body .btn {
        width: 100%;
        margin-top: 10px;
    }
</style>
<div class="container mt-5">
    <h2 style="color: white;">Películas</h2>
</div>
<div class="row mx-auto">
    {% for pelicula in peliculas %}
        <div class="col-md-4 mb-4">
            <div class="card mx-auto">
                {% if pelicula.imagen %}
                    <img src="{{ pelicula.imagen.url }}" class="card-img-top" alt="{{ pelicula.nombre }}" style="max-height: 100%;">
                {% else %}
                    <img src="{% static 'images/not-found.png' %}" class="card-img-top" alt="Sin imagen" style="max-height: 100%;">
                {% endif %}
                <div class="card-body text-center">
                    <h5 class="card-title">{{ pelicula.nombre }}</h5>
                    <p class="card-text"><strong>Género:</strong> {{ pelicula.get_genero_display }}</p>
                    <p class="card-text"><strong>Clasificación:</strong> {{ pelicula.get_clasificacion_display }}</p>
                    <div class="mx-auto detalle-cmpelicula">
                        <a href="{% url 'pelicula-detail' id=pelicula.id %}" class="btn btn-info w-100">Ver</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}